version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: messenger-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: messenger
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: no-reply@messenger.test
    depends_on:
      - db
    networks:
      - messenger

  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: messenger-frontend-build
    command: [ "sh", "-c", "npm install --include=dev && npm run build" ]
    volumes:
      - ./frontend:/app
      - frontend_dist:/app/dist
    networks:
      - messenger

  nginx:
    image: nginx:1.25-alpine
    container_name: messenger-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - frontend_dist:/usr/share/nginx/html   # сюда кладём dist
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend-build
    networks:
      - messenger

  db:
    image: mysql:8
    container_name: messenger-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - messenger

  mailhog:
    image: mailhog/mailhog
    container_name: messenger-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - messenger

volumes:
  db_data:
  frontend_dist:

networks:
  messenger:
    driver: bridge
